<?php
// $Id$

/**
 * @file
 * Module for displaying your latest Dribbble shots.
 *
 * @see http://www.dribbble.com
 */

/**
 * Display help and module information
 * 
 * @param path which path of the site we're displaying help
 * @param arg array that holds the current path as would be returned from arg() function
 * @return help text for the path
 */
function triple_double_help($path, $arg) {
  $output = '';
  switch ($path) {
    case "admin/help#triple_double":
      $output = '<p>' . t('Display your latest Dribbble shots on your Drupal website.') . '</p>';
      break;
  }

  return $output;
}

/**
 * Implementation of hook_perm()
 */
function triple_double_perm() {
  return array('access triple double content', 'administer triple double');
}

/**
 * Implementation of hook_menu()
 */
function triple_double_menu() {
  $items = array();

  $items['admin/settings/triple_double'] = array(
    'title' => 'Triple Double',
    'description' => 'Configure settings for the Triple Double module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('triple_double_settings'),
    'access arguments' => array('administer triple double'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Triple Double Settings page
 *
 * @return settings form
 */
function triple_double_settings() {
  $form = array();

  $form['dribbble_playername'] = array(
    '#type' => 'textfield',
    '#title' => t('Player Name'),
    '#default_value' => variable_get('dribbble_playername', 'dribbble'),
    '#size' => 50,
    '#maxlength' => 255,
    '#description' => t('Your Dribbble Player name'), 
  );

  $form['no_of_shots'] = array(
    '#type' => 'select',
    '#title' => t('No. of Shots'),
    '#default_value' => variable_get('no_of_shots', '1'),
    '#options' => array("1" => "1", "2" => "2", "3" => "3"),
    '#description' => t('No. of Dribbble shots to display.'), 
  );

  return system_settings_form($form);
}

/**
 * Implementation of hook_block()
 */
function triple_double_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      $blocks[0]['info'] = t('Triple Double');
      return $blocks;
    case 'view':
      $shots = "";
      $dribbble_playername = variable_get('dribbble_playername', 'dribbble');
      $no_of_shots = variable_get('no_of_shots', '1');

      // create a new cURL resource
      $results = curl_init();

      // set URL and other appropriate options
      curl_setopt($results, CURLOPT_URL, "http://api.dribbble.com/players/" . $dribbble_playername . "/shots?page=1&per_page=" . $no_of_shots);
      curl_setopt($results, CURLOPT_HEADER, 0);
      curl_setopt($results, CURLOPT_RETURNTRANSFER, 1);

      // Get JSON content
      $json_data = curl_exec($results);

      // close cURL resource, and free up system resources
      curl_close($results);

      // Prepare JSON content for use
      $data = json_decode($json_data);

      // Format your shots
      foreach ($data->{shots} as $shot) {
        $shots .= '<a href="' . $shot->{short_url} . '"><img src="' . $shot->{image_teaser_url} .'" /></a>';
      }

      $blocks['subject'] = t('My Recent Dribbble Shots');
      $blocks['content'] = $shots;
      return $blocks;
  }
}

